# Định nghĩa hình ảnh cơ sở
FROM node:18

# Thiết lập thư mục làm việc
WORKDIR /usr/src/app

# Sao chép các tệp package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các gói npm
RUN npm install

# Sao chép mã nguồn ứng dụng vào thư mục làm việc
COPY . .

# Xây dựng ứng dụng
RUN npm run build dbs-microservice

# Khởi chạy ứng dụng
CMD  ["node", "./dist/apps/dbs-microservice/main.js"]